package com.pieaksoft.event.consumer.android.enums

enum class EventInsertType(val type: String) {
    DUTY_STATUS_CHANGE("DUTY_STATUS_CHANGE"),
    IMMEDIATE_LOG("IMMEDIATE_LOG"),
    CHANGE_IN_DRIVERS_INDICATION_OF_AUTHORIZED_PERSONNEL_USE_OF_CMV_OR_YARD_MOVES("CHANGE_IN_DRIVERS_INDICATION_OF_AUTHORIZED_PERSONNEL_USE_OF_CMV_OR_YARD_MOVES"),
    DRIVERS_CERTIFICATION_RE_CERTIFICATION_OF_RECORDS("DRIVERS_CERTIFICATION_RE_CERTIFICATION_OF_RECORDS"),
    DRIVERS_LOGIN_LOGOUT_ACTIVITY("DRIVERS_LOGIN_LOGOUT_ACTIVITY"),
    CMV_ENGINES_POWER_UP_DOWN_ACTIVITY("CMV_ENGINES_POWER_UP_DOWN_ACTIVITY"),
    MALFUNCTION_OR_DIAGNOSTIC_DETECTION_OCCURRENCE("MALFUNCTION_OR_DIAGNOSTIC_DETECTION_OCCURRENCE"),
    CYCLE_RESET("CYCLE_RESET"),
    NONE("NONE");
}

val dutyStatuses: Array<EventInsertType>
    get() = arrayOf(
        EventInsertType.DUTY_STATUS_CHANGE,
        EventInsertType.CHANGE_IN_DRIVERS_INDICATION_OF_AUTHORIZED_PERSONNEL_USE_OF_CMV_OR_YARD_MOVES
    )

fun String.toInsertType(): EventInsertType {
    return EventInsertType.values().first { it.type.contentEquals(this) }
}
