package com.pieaksoft.event.consumer.android.utils

const val SHARED_PREFERENCES_NAME = "ELD_SHARED_PREFERENCES"
const val SHARED_PREFERENCES_CURRENT_USER_ID = "CURRENT_USER_ID"
const val SHARED_PREFERENCES_MAIN_USER_ID = "MAIN_USER_ID"
const val SHARED_PREFERENCES_ADDITIONAL_USER_ID = "ADDITIONAL_USER_ID"
const val SHARED_PREFERENCES_NOTIFICATION_SETTINGS = "NOTIFICATION_SETTINGS"
const val BROADCAST_SWAP_DRIVERS = "BROADCAST_SWAP_DRIVERS"
const val USER_TIMEZONE = "USER_TIMEZONE"